#!/bin/bash

# ο πραγματικός πυρήνας του ονείρου δεν είναι η λανθάνουσα
# σκέψη του ονείρου η οποία έχει μετατοπιστεί/μεταφραστεί στην
# ρητή υφή του ονείρου, αλλά η ασυνείδητη επιθυμία η οποία
# εγγράφεται μέσω της ίδιας της παραμόρφωσης της λανθάνουσας
# σκέψης στην ρητή υφή.

PROG=$(basename $0)
CMLINE='java -jar .*vismo.jar'
PIDFILE=/tmp/"$PROG".pid


start() {
	nohup java -jar target/vismo-1.0.0-SNAPSHOT.jar >/dev/null 2>&1 &
}

stop() {
	kill $(cat "$PIDFILE")
	sleep 1
	pkill -f "$CMLINE"
}

restart() {
	stop
	sleep 1
	start
}

pidfile_status() {
	test -r "$PIDFILE" || { echo no pid file; return 1; }
	ps -p $(cat "$PIDFILE") >/dev/null 2>&1 ||
		{ echo no proc with pid $(cat "$PIDFILE"); return 1; }
	echo $(cat "$PIDFILE")
	return 0
}

grep_status() {
	echo 2
}

status() {
	echo "$PROG: $(pidfile_status)"
	echo "$PROG: $(grep_status)"
}

case "$1" in
	start) start ;;
	stop) stop ;;
	restart) restart ;;
	status) status ;;
	*) echo "usage: $0 {start|stop|status|restart}" ;;
esac

exit 0
